version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    command: redis-server
    volumes:
      - redis:/data
  web:
    build: .
    env_file:
      - .env
    command: ./bin/start.sh
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0
  scan_goerli_lcmp_logs:
    build: .
    env_file:
      - .env
    command: /bin/bash -c "RAILS_ENV=production bundle exec rails goerli_pangolin_lcmp:scan_events_of_goerli"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  scan_pangolin_lcmp_logs:
    build: .
    env_file:
      - .env
    command: /bin/bash -c "RAILS_ENV=production bundle exec rails goerli_pangolin_lcmp:scan_events_of_pangolin"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

volumes:
  redis:
  postgres:
