default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL_CABLE") { "redis://redis:6379/1" } %>

development:
  <<: *default

test:
  adapter: test

production:
  <<: *default
  channel_prefix: msgscan_production
